# on:
#   push:
#     paths:
#       - '.github/workflows/*'
#
# jobs:
#   lint:
#     uses: sasaplus1/reusable-workflows/.github/workflows/lint-workflows.yml@main

on:
  workflow_call:

jobs:
  lint-workflow-files:
    name: lint workflow files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: docker://rhysd/actionlint:latest
